SLUGS/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from SLUGS import views
from django.contrib.auth import views as auth_views
from gig.views import AttachmentDownload, VendorDownload
from employee.views import FormDownload, FilledFormDownload
from finance.views import EstimateDownload
from django.views.generic.base import RedirectView


urlpatterns = [
    path("unicorn/", include("django_unicorn.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("hijack/", include("hijack.urls")),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('.well-known/openid-configuration', RedirectView.as_view(url='/openid/.well-known/openid-configuration', permanent=False), name='openid-configuration'),
    path("admin/", admin.site.urls),
    path(
        "media/forms/<path:relative_path>", FormDownload.as_view(), name="download_form"
    ),
    path(
        "media/uploads/<u_pk>/<path:relative_path>",
        FilledFormDownload.as_view(),
        name="download_form",
    ),
    path(
        "media/estimates/<path:relative_path>",
        EstimateDownload.as_view(),
        name="download_estimate",
    ),
    path(
        "media/attachments/<path:relative_path>",
        AttachmentDownload.as_view(),
        name="download_attachment",
    ),
    path(
        "media/vendors/<path:relative_path>",
        VendorDownload.as_view(),
        name="download_vendor_form",
    ),
    path(
        "auth/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_html_email.html"
        ),
    ),
    path("auth/", include("django.contrib.auth.urls"), name="auth"),
    path("utils/", include("utils.urls")),
    path("", views.index.as_view(), name="index"),
    path("kiosk/", views.kiosk.as_view(), name="kiosk"),
    path("employee/", include("employee.urls")),
    path("gig/", include("gig.urls")),
    path("equipment/", include("equipment.urls")),
    path("training/", include("training.urls")),
    path("finance/", include("finance.urls")),
]

employee/urls.py
from django.urls import path
from . import views

app_name = "employee"
urlpatterns = [
    path("onboard", views.userSignup.as_view(), name="signup"),
    path("onboard/success", views.userSignupComplete.as_view(), name="signup_complete"),
    path("view", views.userOverview.as_view(), name="overview"),
    path("password/change", views.changePassword.as_view(), name="change_password"),
    path("office_hours", views.officeHours.as_view(), name="office_hours"),
    path("form/<form_id>/upload", views.uploadForm.as_view(), name="upload_form"),
    path(
        "form/<form_id>/sign", views.automaticallySignForm.as_view(), name="sign_form"
    ),
    path(
        "mass-assign-paperwork/<selected>",
        views.massAssignPaperwork.as_view(),
        name="mass_assign",
    ),
    path(
        "add-groups/<selected>",
        views.addGroups.as_view(),
        name="add_groups",
    ),
]

finance/urls.py
from django.urls import path
from . import views

app_name = "finance"
urlpatterns = [
    path("", views.FinancialOverview.as_view(), name="overview"),
    path("estimate/<e_id>", views.viewEstimate.as_view(), name="estimate"),
    path("invoice/<e_id>", views.viewInvoice.as_view(), name="invoice"),
    path("vendor/<v_id>", views.viewSubcontractedEquipment.as_view(), name="vendor"),
    path("timesheet/<timesheet_id>", views.viewTimesheet.as_view(), name="timesheet"),
    path(
        "noprint/timesheet/<timesheet_id>",
        views.ViewTimesheetXframe.as_view(),
        name="timesheetxframe",
    ),
    path(
        "sign/timesheet/<timesheet_id>",
        views.SignTimesheet.as_view(),
        name="sign_timesheet",
    ),
    path("summary/<pp_id>/", views.viewSummary.as_view(), name="summary"),
    path("summary_csv/<pp_id>/", views.exportSummaryCSV.as_view(), name="summary_csv"),
    path("summary_paychex_csv/<pp_id>/", views.exportSummaryPayChexCSV.as_view(), name="summary_paychex_csv"),
    path(
        "summary/sa_billing/<month>/<year>/",
        views.saBillingSummary.as_view(),
        name="sa_billing_summary",
    ),
]

gig/urls.py
from django.urls import path
from . import views

app_name = "gig"
urlpatterns = [
    path("signup/", views.workSignup.as_view(), name="signup"),
    path("list/", views.gigList.as_view(), name="list"),
    path("joblist/", views.DistinctGigJobsList.as_view(), name="joblist"),
    path("booking/", views.BookingOverview.as_view(), name="booking_overview"),
    path("<gig_id>/", views.gigIndex.as_view(), name="showView"),
    path(
        "<gig_id>/staff_email_template",
        views.generateEmailTemplate.as_view(),
        name="staff_email_template",
    ),
]

training/urls.py
from django.urls import path
from . import views

app_name = "training"
urlpatterns = [
    path("", views.index.as_view(), name="index"),
]

SLUGS/views.py
from django.db.models.query_utils import Q
from django.views.generic.base import TemplateView
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse
from django.utils import timezone
from employee.models import Employee
from training.models import Training
from utils.models import Notification, signupStatus
from gig.models import Gig, Job
from SLUGS.templatetags.grouping import has_group


def get_closest_to_dt(qs, dt):
    greater = qs.filter(dt__gte=dt).order_by("dt").first()
    less = qs.filter(dt__lte=dt).order_by("-dt").first()

    if greater and less:
        return greater if abs(greater.dt - dt) < abs(less.dt - dt) else less
    else:
        return greater or less


class isAdminMixin:
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect("%s?next=%s" % (reverse("login"), request.path))
        return super().dispatch(request, *args, **kwargs)


class SLUGSMixin:
    added_context = {}

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("%s?next=%s" % (reverse("login"), request.path))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.added_context)
        return context


class index(SLUGSMixin, TemplateView):
    template_name = "SLUGS/index.html"

    def dispatch(self, request, *args, **kwargs):
        self.added_context["notifications"] = Notification.objects.all()
        self.added_context["signup_open"] = signupStatus.objects.first().is_open
        self.added_context["gigs"] = (
            (
                Gig.objects.filter(job__employee=request.user)
                .distinct()
                .order_by("-start")
            )
            if request.user.is_authenticated
            else None
        )
        if request.user.is_authenticated:
            if has_group(request.user, "SA Employee"):
                return redirect("/admin")
            next_gig_id = (
                Job.objects.filter(employee=request.user)
                .filter(gig__end__gte=(timezone.now() - timezone.timedelta(hours=5)))
                .values(
                    "gig__id",
                )
                .order_by("gig__end")[:1]
            )
            self.added_context["next_gig"] = (
                Gig.objects.get(pk=next_gig_id[0]["gig__id"])
                if (len(next_gig_id) > 0)
                else None
            )
            self.added_context[
                "outstanding_paperwork"
            ] = request.user.paperworkform_set.filter(
                Q(processed=False)
                & (
                    Q(form__required_for_employment=True)
                    | Q(form__required_for_payroll=True)
                )
            )
        return super().dispatch(request, *args, **kwargs)


class kiosk(TemplateView):
    added_context = {}
    template_name = "SLUGS/kiosk.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.added_context)
        return context

    def dispatch(self, request, *args, **kwargs):
        if not (request.COOKIES.get('SLUGSKiosk') and Employee.objects.get(pk=request.COOKIES.get('SLUGSKiosk')).is_staff):
            raise PermissionDenied()
        return super().dispatch(request, *args, **kwargs)

SLUGS/templates/SLUGS/components/nav.html
{% load static %}
{% load grouping %}
{% load timeline %}
<nav class="flex px-4 text-black bg-white">
    <a href="/">
        <img class="w-14 h-14 sm:w-20 sm:h-20 filter hover:invert-[.5]" src="{% static 'img/logo/logo.svg' %}" />
    </a>
    <div class="my-auto space-x-4 text-lg font-bold">
        <a class="hover:text-gray-600" href="{% url 'gig:list' %}">Shows</a>
        <a class="hover:text-gray-600" href="{% url 'training:index' %}">Training</a>
        <a class="hover:text-gray-600" href="{% url 'employee:overview' %}">You</a>
        {% if request.user.is_staff %} 
        <!-- Show admin to all staff (Managers and SA) but not office hours -->
        <a class="hidden md:inline hover:text-gray-600" href="{% url 'admin:index' %}">Admin</a>
        {% endif %}
        {% if request.user|has_group:"Manager" %}
        <a class="hidden md:inline hover:text-gray-600" href="{% url 'employee:office_hours' %}">Office Hours</a>
        <a class="hidden md:inline hover:text-gray-600" href="{% url 'gig:booking_overview' %}">Booking</a>
        {% if request.user|has_group:"Financial Director/GM" %}<a class="hidden md:inline hover:text-gray-600" href="{% url 'finance:overview' %}">Finance</a>{% endif %}
        {% endif %}
    </div>
    <div class="my-auto ml-auto mr-0">
        <div class="relative hidden md:block" tabindex="0">
            <a href="#"><span>Hey there,</span>
                {% if request.user.preferred_name %}{{request.user.preferred_name}} {% else %} {{request.user.first_name}} {% endif %}</a>
            <div
                class="absolute w-full h-0 mt-5 overflow-hidden transition-all duration-75 bg-white shadow focused-within-parent:h-28">
                <div class="flex flex-col py-5">
                    <a class="mx-auto" href="mailto:slugs@joebabbitt.com">Help!</a>
                    <hr class="my-2"/>
                    <a class="mx-auto" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </div>
        <div tabindex="0" onclick="openMenu()" class="text-black md:hidden">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
        </div>
    </div>
</nav>
{% if signup_open %}
<a class="text-black" href="{% url 'gig:signup' %}">
    <div class="flex w-full h-10 bg-red-300">
        <div class="flex mx-auto my-auto space-x-4">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24"
            stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
            </svg>
            <span class="mx-auto">Work is available for signup! Click here to signup</span>
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
            </svg>
        </div>
    </div>
</a>
{% endif %}
{% timeline request.user %}
<div onclick="closeMenu()" class="absolute top-0 z-40 hidden w-screen h-screen transition-all bg-black opacity-75 menubackground"></div>
<div class="fixed top-0 right-0 z-50 w-4/6 h-screen text-black transition-all transform translate-x-full bg-white shadow mobile-nav">
    <div class="flex flex-col mt-10">
        <div tabindex="0" onclick="closeMenu()" class="p-2 mx-auto rounded">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
        </div>
        {% if request.user|has_group:"Manager" or request.user.is_staff %}
        <div class="flex flex-col mt-5 ml-5 space-y-4">
            {% if request.user|has_group:"Manager" %}
            <a class="text-lg font-bold underline" href="{% url 'admin:index' %}">Admin</a>
            <a class="text-lg font-bold underline" href="{% url 'employee:office_hours' %}">Office Hours</a>
            <a class="text-lg font-bold underline" href="{% url 'gig:booking_overview' %}">Booking</a>
            {% endif %}
            {% if request.user|has_group:"Financial Director/GM" %}<a class="text-lg font-bold underline" href="{% url 'finance:overview' %}">Finance</a>{% endif %}
            <hr/>
        </div>
        {% endif %}
        <div class="flex flex-col mt-5 ml-5 space-y-4">
            <a class="text-lg font-bold underline" href="sms:19176516798">Get Help!</a>
            <a class="text-lg font-bold underline" href="{% url 'logout' %}">Logout</a>
        </div>
    </div>
</div>
<script>
    const openMenu = () => {
        document.querySelector('.menubackground').classList.remove('hidden')
        document.querySelector('.mobile-nav').classList.remove('translate-x-full')
        document.querySelector('body').classList.add('overflow-hidden')
    }
    const closeMenu = () => {
        document.querySelector('.menubackground').classList.add('hidden')
        document.querySelector('.mobile-nav').classList.add('translate-x-full')
        document.querySelector('body').classList.remove('overflow-hidden')
    }
</script>

SLUGS/templates/SLUGS/components/print.html
<script>
    print()
</script>