SLUGS/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from SLUGS import views
from django.contrib.auth import views as auth_views
from gig.views import AttachmentDownload, VendorDownload
from employee.views import FormDownload, FilledFormDownload
from finance.views import EstimateDownload
from django.views.generic.base import RedirectView


urlpatterns = [
    path("unicorn/", include("django_unicorn.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("hijack/", include("hijack.urls")),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('.well-known/openid-configuration', RedirectView.as_view(url='/openid/.well-known/openid-configuration', permanent=False), name='openid-configuration'),
    path("admin/", admin.site.urls),
    path(
        "media/forms/<path:relative_path>", FormDownload.as_view(), name="download_form"
    ),
    path(
        "media/uploads/<u_pk>/<path:relative_path>",
        FilledFormDownload.as_view(),
        name="download_form",
    ),
    path(
        "media/estimates/<path:relative_path>",
        EstimateDownload.as_view(),
        name="download_estimate",
    ),
    path(
        "media/attachments/<path:relative_path>",
        AttachmentDownload.as_view(),
        name="download_attachment",
    ),
    path(
        "media/vendors/<path:relative_path>",
        VendorDownload.as_view(),
        name="download_vendor_form",
    ),
    path(
        "auth/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_html_email.html"
        ),
    ),
    path("auth/", include("django.contrib.auth.urls"), name="auth"),
    path("utils/", include("utils.urls")),
    path("", views.index.as_view(), name="index"),
    path("kiosk/", views.kiosk.as_view(), name="kiosk"),
    path("employee/", include("employee.urls")),
    path("gig/", include("gig.urls")),
    path("equipment/", include("equipment.urls")),
    path("training/", include("training.urls")),
    path("finance/", include("finance.urls")),
]

gig/urls.py
from django.urls import path
from . import views

app_name = "gig"
urlpatterns = [
    path("signup/", views.workSignup.as_view(), name="signup"),
    path("list/", views.gigList.as_view(), name="list"),
    path("joblist/", views.DistinctGigJobsList.as_view(), name="joblist"),
    path("booking/", views.BookingOverview.as_view(), name="booking_overview"),
    path("<gig_id>/", views.gigIndex.as_view(), name="showView"),
    path(
        "<gig_id>/staff_email_template",
        views.generateEmailTemplate.as_view(),
        name="staff_email_template",
    ),
]

utils/urls.py
from django.urls import path
from . import models
from . import views

app_name = "utils"
urlpatterns = [
    path("latest/events.ics", models.ShowFeed(), name="showFeed"),
    path(
        "latest/tentative_events.ics",
        models.TentativeShowFeed(),
        name="tentativeShowFeed",
    ),
    path("latest/lighting_work.ics", models.LightingFeed(), name="lightingFeed"),
    path("latest/sound_work.ics", models.SoundFeed(), name="soundFeed"),
    path("latest/stage_work.ics", models.StageFeed(), name="stageFeed"),
    path("<emp_id>/shifts.ics", models.EmployeeFeed(), name="employeeFeed"),
    path("server/restart", views.restartServer.as_view(), name="restartServer"),
]

SLUGS/views.py
from django.db.models.query_utils import Q
from django.views.generic.base import TemplateView
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse
from django.utils import timezone
from employee.models import Employee
from training.models import Training
from utils.models import Notification, signupStatus
from gig.models import Gig, Job
from SLUGS.templatetags.grouping import has_group


def get_closest_to_dt(qs, dt):
    greater = qs.filter(dt__gte=dt).order_by("dt").first()
    less = qs.filter(dt__lte=dt).order_by("-dt").first()

    if greater and less:
        return greater if abs(greater.dt - dt) < abs(less.dt - dt) else less
    else:
        return greater or less


class isAdminMixin:
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect("%s?next=%s" % (reverse("login"), request.path))
        return super().dispatch(request, *args, **kwargs)


class SLUGSMixin:
    added_context = {}

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("%s?next=%s" % (reverse("login"), request.path))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.added_context)
        return context


class index(SLUGSMixin, TemplateView):
    template_name = "SLUGS/index.html"

    def dispatch(self, request, *args, **kwargs):
        self.added_context["notifications"] = Notification.objects.all()
        self.added_context["signup_open"] = signupStatus.objects.first().is_open
        self.added_context["gigs"] = (
            (
                Gig.objects.filter(job__employee=request.user)
                .distinct()
                .order_by("-start")
            )
            if request.user.is_authenticated
            else None
        )
        if request.user.is_authenticated:
            if has_group(request.user, "SA Employee"):
                return redirect("/admin")
            next_gig_id = (
                Job.objects.filter(employee=request.user)
                .filter(gig__end__gte=(timezone.now() - timezone.timedelta(hours=5)))
                .values(
                    "gig__id",
                )
                .order_by("gig__end")[:1]
            )
            self.added_context["next_gig"] = (
                Gig.objects.get(pk=next_gig_id[0]["gig__id"])
                if (len(next_gig_id) > 0)
                else None
            )
            self.added_context[
                "outstanding_paperwork"
            ] = request.user.paperworkform_set.filter(
                Q(processed=False)
                & (
                    Q(form__required_for_employment=True)
                    | Q(form__required_for_payroll=True)
                )
            )
        return super().dispatch(request, *args, **kwargs)


class kiosk(TemplateView):
    added_context = {}
    template_name = "SLUGS/kiosk.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.added_context)
        return context

    def dispatch(self, request, *args, **kwargs):
        if not (request.COOKIES.get('SLUGSKiosk') and Employee.objects.get(pk=request.COOKIES.get('SLUGSKiosk')).is_staff):
            raise PermissionDenied()
        return super().dispatch(request, *args, **kwargs)

SLUGS/templates/SLUGS/index.html
{% extends "theme/base.html" %}
{% load grouping %}
{% load static %}
{% load gig_components %}
{% load tz %}
{% load i18n %}


{% block title %}Dashboard{% endblock %}
{% block content %}
<div class="flex flex-col mx-auto max-w-7xl">
    <div class="mx-4 mt-10 space-y-10 sm:mx-10">
        <div>
            <h1 class="text-4xl text-bold">
                Notifications
            </h1>
            <div class="flex flex-col my-4 space-y-4">
                {% if request.user|show_notifications:notifications or signup_open %}
                <style>
                    .notification a {
                        text-decoration: underline;
                    }
                </style>
                {% for notification in notifications %}
                {% if request.user|show_notification:notification %}
                <div class="notification max-w-5xl mx-auto rounded-sm py-2 px-4 {{notification.message_type}}">
                    {{notification.message|safe}}
                </div>
                {% endif %}
                {% endfor %}
                {% if outstanding_paperwork %}
                <div class="max-w-5xl px-4 py-2 mx-auto bg-red-500 rounded-sm notification">
                    <h1>{% translate "Unfortunately you have paperwork we're still waiting for. Please hand it in!" %}</h1>
                    <p class="text-sm">If you've handed in one of these forms but still see it on this list. It may still be in processing</p>
                    <ul class="ml-4">
                        {% for paperwork in outstanding_paperwork %}
                        <li class="list-disc">
                            {{paperwork.form.form_name}} {% if paperwork.uploaded %}<sub>(We see that this has been uploaded. Just waiting on processing)</sub>{% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
                {% if signup_open %}
                <a class="" href="{% url 'gig:signup' %}">
                    <div
                        class="flex max-w-5xl px-12 py-6 mx-auto text-center text-black transition bg-red-300 rounded-sm hover:bg-red-200">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
                        </svg>
                        <div style="margin: auto;">{% translate "Click here to sign up for this week's work" %} {% if request.user|has_group:"Cannot Work" %}<br> <span style="font-weight: bold; font-size: .75rem;">{% translate "(well not for you bc you still haven't handed in all your paperwork)" %}</span>  {% endif %}</div>
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
                        </svg>
                    </div>
                </a>
                {% endif %}
                {% else %}
                <div class="text-center mx-auto text-xl p-4 rounded bg-[#1F1F1F]" id="no_notifications">Nothing's here.... for now 😳</div>
                {% endif %}
            </div>
        </div>
        <div>
            {% if next_gig %}
            <h1 class="text-4xl text-bold"> Next Show</h1>
                {% if next_gig.published %}
                    <a href="{% url 'gig:showView' next_gig.pk %}">
                    {% ticket next_gig %}
                    </a>
                {% else %}
                    {% ticket next_gig %}
                {% endif %}
            {% endif %}
        </div>
        <div>
            <h1 class="text-4xl text-bold">
                My shows
            </h1>
            <div class="my-4 md:mx-20 break-text">
                <div class="flex p-4 text-black bg-green-100 rounded-sm">
                    <div class="p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                          </svg>
                    </div>
                    <div class="w-11/12 mx-auto" tabindex="0">
                        <div class="flex">
                            <p class="font-bold">
                                Did you know you can have your shows automatically added to your Calendar?
                            </p>
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 ml-auto mr-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                            </svg>
                        </div>
                        <div class="h-0 px-2 overflow-hidden transition-all focused-within-parent:h-full">
                            <p>
                                Follow the steps below to get started. Once added, your calendar will be updated every 24 hours with your latest shifts.
                            </p>
                            <ol class="px-4 list-decimal">
                                <li class="break-words">
                                    Go to <a class="underline" href="https://calendar.google.com/calendar/r/settings/addbyurl">https://calendar.google.com/calendar/r/settings/addbyurl</a>
                                </li>
                                <li class="break-words">
                                    Enter <b>https://{{request.get_host}}{% url 'utils:employeeFeed' emp_id=request.user.pk %}</b> as the URL
                                </li>
                                <li>
                                    Hit Add Calendar
                                </li>
                            </ol>
                            <p class="text-sm"> If you're looking for instructions for calendars other than Google Calendar, see <a class="underline" href="https://bssl.binghamtonsa.org/employee-resources/" target="_blank">our website</a> for alternate instructions</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="my-4 md:mx-20">
                {% if gigs.count > 0 %}
                <table style="border-spacing: 1rem 1rem;" class="w-full table-auto">
                    <thead class="border-b-2 border-white">
                        <tr>
                            <td>
                                Name
                            </td>
                            <td class="hidden md:inline">
                                Organization
                            </td>
                            <td>
                                Location
                            </td>
                            <td>
                                When
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for gig in gigs %}
                        <tr tabindex="0" {% if gig.published %} onclick="window.location='{% url 'gig:showView' gig.id %}'" class="cursor-pointer even:bg-[#1F1F1F] odd:bg-[#333333] hover:bg-gray-700"  {% else %} class="even:bg-[#1F1F1F] odd:bg-[#333333]" {% endif %}>
                            <td class="pl-2">
                                {{gig.name}}
                            </td>
                            <td class="hidden pl-2 md:table-cell">
                                {{gig.org}}
                            </td>
                            <td class="py-4 pl-2">
                                {{gig.location}}
                            </td>
                            <td class="pl-2">
                                {{gig.start}}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <div class="bg-[#1F1F1F] p-5 text-center text-xl text-white">
                    You have no gigs...
                    <img class="w-24 h-24 mx-auto my-4" src="{% static 'img/index/vibe_check.png' %}"/>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

SLUGS/templates/SLUGS/kiosk.html
{% extends "theme/base.html" %}
{% load grouping %}
{% load static %}
{% load tz %}
{% load unicorn %}

{% block nav %} {% endblock %}
{% block title %}Kiosk{% endblock %}
{% block headincludes %} {% unicorn_scripts %} {% endblock %}
{% block content %}
<div class="flex">
    <img src="{% static 'img/logo/logo.png' %}" class="h-20 my-auto filter invert" alt="SLUGS logo"/>
    <h1 class="my-auto text-6xl">
        <span class="my-auto font-stencil">SLUGS</span> Self Service
    </h1>
</div>
<div class="flex flex-col max-w-5xl mx-auto mt-10 w-max">
    <div class="p-4 mx-auto text-black bg-white">
        <h1 class="text-4xl text-center">Current Time:</h1>
        <h1 id="currtime" class="text-4xl text-center" style="font-family: monospace;"></h1>
        <script>
            const currtime = document.querySelector("#currtime")
            setInterval(() => {
                currtime.innerHTML = (new Date()).toLocaleString()
            }, 450);
        </script>
        <!-- <h1 class="text-4xl text-center">Scan ID to see personalized options</h1>
        <div class="flex flex-col my-2">
            <input class="mx-auto text-white bg-gray-800 rounded-sm w-52" type="text"/>
            <div class="flex p-2 my-2 bg-blue-300 rounded-sm">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12zm8.706-1.442c1.146-.573 2.437.463 2.126 1.706l-.709 2.836.042-.02a.75.75 0 01.67 1.34l-.04.022c-1.147.573-2.438-.463-2.127-1.706l.71-2.836-.042.02a.75.75 0 11-.671-1.34l.041-.022zM12 9a.75.75 0 100-1.5.75.75 0 000 1.5z" clip-rule="evenodd" />
                </svg>
                <p>
                    Don't have your ID? Have the Engineer scan theirs or use your phone instead
                </p>         
            </div>
        </div> -->
    </div>
</div>
<div class="flex mt-6 ml-10 mr-6 space-x-4">
    <div class="w-2/3 p-4 text-black bg-white rounded-sm">
        <h2 class="text-2xl text-center">Ongoing Shows</h2>
        {% unicorn 'kioskShow'%}
        <div class="grid 
            {% if ongoing_shows|length == 1 %}
                grid-cols-1
            {% elif ongoing_shows|length == 2 %}
                grid-cols-2
            {% else %}
                grid-cols-3
            {% endif %}
            gap-2 auto-rows-fr ">
        </div>
    </div>
    <div class="w-1/3 p-4 text-black bg-white rounded-sm">
        <h2 class="text-2xl text-center">Ongoing Trainings</h2>
        {% unicorn 'kioskTraining'%}
    </div>
</div>
{% endblock %}
{% block footer %} {% endblock %}