SLUGS/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from SLUGS import views
from django.contrib.auth import views as auth_views
from gig.views import AttachmentDownload, VendorDownload
from employee.views import FormDownload, FilledFormDownload
from finance.views import EstimateDownload
from django.views.generic.base import RedirectView


urlpatterns = [
    path("unicorn/", include("django_unicorn.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("hijack/", include("hijack.urls")),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('.well-known/openid-configuration', RedirectView.as_view(url='/openid/.well-known/openid-configuration', permanent=False), name='openid-configuration'),
    path("admin/", admin.site.urls),
    path(
        "media/forms/<path:relative_path>", FormDownload.as_view(), name="download_form"
    ),
    path(
        "media/uploads/<u_pk>/<path:relative_path>",
        FilledFormDownload.as_view(),
        name="download_form",
    ),
    path(
        "media/estimates/<path:relative_path>",
        EstimateDownload.as_view(),
        name="download_estimate",
    ),
    path(
        "media/attachments/<path:relative_path>",
        AttachmentDownload.as_view(),
        name="download_attachment",
    ),
    path(
        "media/vendors/<path:relative_path>",
        VendorDownload.as_view(),
        name="download_vendor_form",
    ),
    path(
        "auth/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_html_email.html"
        ),
    ),
    path("auth/", include("django.contrib.auth.urls"), name="auth"),
    path("utils/", include("utils.urls")),
    path("", views.index.as_view(), name="index"),
    path("kiosk/", views.kiosk.as_view(), name="kiosk"),
    path("employee/", include("employee.urls")),
    path("gig/", include("gig.urls")),
    path("equipment/", include("equipment.urls")),
    path("training/", include("training.urls")),
    path("finance/", include("finance.urls")),
]

employee/urls.py
from django.urls import path
from . import views

app_name = "employee"
urlpatterns = [
    path("onboard", views.userSignup.as_view(), name="signup"),
    path("onboard/success", views.userSignupComplete.as_view(), name="signup_complete"),
    path("view", views.userOverview.as_view(), name="overview"),
    path("password/change", views.changePassword.as_view(), name="change_password"),
    path("office_hours", views.officeHours.as_view(), name="office_hours"),
    path("form/<form_id>/upload", views.uploadForm.as_view(), name="upload_form"),
    path(
        "form/<form_id>/sign", views.automaticallySignForm.as_view(), name="sign_form"
    ),
    path(
        "mass-assign-paperwork/<selected>",
        views.massAssignPaperwork.as_view(),
        name="mass_assign",
    ),
    path(
        "add-groups/<selected>",
        views.addGroups.as_view(),
        name="add_groups",
    ),
]

gig/urls.py
from django.urls import path
from . import views

app_name = "gig"
urlpatterns = [
    path("signup/", views.workSignup.as_view(), name="signup"),
    path("list/", views.gigList.as_view(), name="list"),
    path("joblist/", views.DistinctGigJobsList.as_view(), name="joblist"),
    path("booking/", views.BookingOverview.as_view(), name="booking_overview"),
    path("<gig_id>/", views.gigIndex.as_view(), name="showView"),
    path(
        "<gig_id>/staff_email_template",
        views.generateEmailTemplate.as_view(),
        name="staff_email_template",
    ),
]

employee/views.py
from django.urls.base import reverse
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.views import View
from django.core.mail import EmailMessage
from django.template.loader import get_template
import django.utils.timezone as timezone
from django.conf import settings
from django.http import FileResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.models import Group
from django.db.models import Sum
from django.core.exceptions import PermissionDenied, ValidationError
from django.contrib.admin.models import LogEntry, CHANGE
from employee.forms import (
    massAssignPaperworkForm,
    addGroupsForm,
    signPaperworkForm,
    userCreationForm,
    userChangeForm,
    changePasswordForm,
    uploadForm,
)
from dev_utils.views import MultipleFormView
from SLUGS.views import SLUGSMixin, isAdminMixin
from employee.utils import processAutoSignForm
from utils.models import onboardingStatus
from finance.utils import getShiftsForEmployee
from finance.forms import OfficeHoursShiftFormSet
from finance.models import Shift, TimeSheet
from employee.models import OfficeHours, PaperworkForm, Employee


# Create your views here.
class userSignup(FormView):
    form_class = userCreationForm
    success_url = "/employee/onboard/success"
    template_name = "employee/signup.html"

    def dispatch(self, request, *args, **kwargs):
        signup = onboardingStatus.objects.first()
        if signup.is_open is not True:
            raise PermissionDenied()
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        template = get_template("employee/components/signup_email.html")
        email_template = template.render({"user": form.instance})
        email = EmailMessage(
            subject="Thanks for signing up for SLUGS",
            body=email_template,
            from_email="bssl.slugs@binghamtonsa.org",
            to=[form.instance.email],
            reply_to=[settings.BSSL_EMAIL_ADDRESS],
        )
        email.content_subtype = "html"
        email.send()
        return super().form_valid(form)


class userSignupComplete(TemplateView):
    template_name = "employee/signup_complete.html"


class userOverview(SLUGSMixin, MultipleFormView):
    template_name = "employee/overview.html"
    form_classes = {"userChangeForm": {"form": userChangeForm}}

    def process_forms(self, form_instances):
        for form in form_instances["forms"]:
            form_instances["forms"][form].save()
        messages.add_message(
            self.request, messages.SUCCESS, "We've updated your information 👍"
        )
        return self.render_to_response(self.get_context_data())

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("%s?next=%s" % (reverse("login"), request.path))
        self.form_classes["userChangeForm"]["instance"] = request.user
        self.added_context["timesheets"] = TimeSheet.objects.filter(
            employee=request.user
        ).order_by('-paid_during__start')
        self.added_context["unsigned_tms"] = self.added_context["timesheets"].filter(signed=None)
        self.added_context["tms_by_year"] = {}
        for year in reversed(range(self.added_context["timesheets"].last().paid_during.start.year, self.added_context["timesheets"].first().paid_during.start.year+1)):
            self.added_context["tms_by_year"][year] = self.added_context["timesheets"].filter(paid_during__start__year=year).exclude(signed=None)
        self.added_context["shifts"] = getShiftsForEmployee(request.user)

        self.added_context["paperwork"] = PaperworkForm.objects.filter(
            employee=request.user
        ).order_by('requested')
        self.added_context["unprocessed_paperwork"] = self.added_context["paperwork"].filter(processed=False)
        self.added_context["paperwork"] = self.added_context["paperwork"].filter(processed=True)

        self.added_context["timeworked"] = self.added_context["shifts"].aggregate(
            Sum("total_time")
        )
        self.added_context["processed_shifts"] = (
            self.added_context["shifts"]
            .order_by("-time_out")
            .filter(processed=True)[:500]
        )
        self.added_context["amount_made"] = self.added_context[
            "processed_shifts"
        ].aggregate(Sum("cost"))
        self.added_context["unprocessed_shifts"] = (
            self.added_context["shifts"]
            .order_by("-time_out")
            .filter(processed=False, contested=False)
        )
        self.added_context["contested_shifts"] = (
            self.added_context["shifts"].order_by("-time_out").filter(contested=True)
        )
        return super().dispatch(request, *args, **kwargs)


class officeHours(SLUGSMixin, MultipleFormView):
    template_name = "employee/office_hours.html"

    def dispatch(self, request, *args, **kwargs):
        self.form_classes = {}
        self.added_context = {"form_meta": {}}
        if Group.objects.get(name="Manager") not in request.user.groups.all():
            raise PermissionDenied()
        try:
            OfficeHours.objects.get_or_create(employee=request.user)
        except Exception:
            pass
        for office_hour_obj in OfficeHours.objects.filter(employee=request.user):
            self.added_context["form_meta"][f"office_hours_{office_hour_obj.pk}"] = {
                "obj": office_hour_obj,
                "rate": office_hour_obj.position,
            }
            self.form_classes[f"office_hours_{office_hour_obj.pk}"] = {
                "form": OfficeHoursShiftFormSet,
                "kwargs": {
                    "queryset": Shift.objects.filter(
                        object_id=office_hour_obj.id,
                        content_type_id=ContentType.objects.get(model="officehours").id,
                        processed=False,
                    ),
                },
            }
        return super().dispatch(request, *args, **kwargs)

    def process_forms(self, form_instances):
        try:
            for form in form_instances["forms"]:
                office_hour_obj = self.added_context["form_meta"][form]["obj"]
                for shift in form_instances["forms"][form].forms:
                    if (
                        shift.instance.time_in is not None
                        and shift.instance.time_out is not None
                    ):
                        shift.instance.object_id = office_hour_obj.id
                        shift.instance.content_type_id = ContentType.objects.get(
                            model="officehours"
                        ).id
                        shift.clean()
                        shift.save()
                form_instances["forms"][form].save()
            messages.add_message(self.request, messages.SUCCESS, "Office Hours updated")
        except ValidationError as err:
            messages.add_message(self.request, messages.ERROR, err.message)
        return self.render_to_response(self.get_context_data())


class changePassword(SLUGSMixin, FormView):
    form_class = changePasswordForm
    template_name = "employee/change_password.html"
    success_url = reverse_lazy("employee:overview")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request, messages.SUCCESS, "Password successfully updated"
        )
        return super().form_valid(form)


class uploadForm(SLUGSMixin, FormView):
    form_class = uploadForm
    template_name = "employee/upload_form.html"
    success_url = reverse_lazy("employee:overview")
    form_id = None

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.form_id
        return kwargs

    def dispatch(self, request, *args, **kwargs):
        if request.user.pk is not None:
            self.form_id = PaperworkForm.objects.get(pk=kwargs["form_id"])
            if self.form_id.employee.pk != request.user.pk:
                raise PermissionDenied()
            self.added_context["paperwork"] = self.form_id
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.uploaded = timezone.now()
        form.save()
        messages.add_message(
            self.request, messages.SUCCESS, f"{form.instance.form} uploaded"
        )
        return super().form_valid(form)


class automaticallySignForm(SLUGSMixin, FormView):
    form_class = signPaperworkForm
    template_name = "employee/automatically_sign_form.html"
    success_url = reverse_lazy("employee:overview")

    def dispatch(self, request, *args, **kwargs):
        if request.user.pk is not None:
            self.form_id = PaperworkForm.objects.get(pk=kwargs["form_id"])
            if self.form_id.employee.pk != request.user.pk:
                raise PermissionDenied()
            self.added_context["paperwork"] = self.form_id
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        processAutoSignForm(self.added_context["paperwork"], self.request.user, Employee.objects.all())
        LogEntry.objects.log_action(
            user_id=self.request.user.pk,
            content_type_id=ContentType.objects.get_for_model(
                self.added_context["paperwork"], for_concrete_model=False
            ).pk,
            object_id=self.added_context["paperwork"].pk,
            object_repr=str(self.added_context["paperwork"]),
            action_flag=CHANGE,

employee/templates/employee/add_groups.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}
{% load gig_admin %}
{% load crispy_forms_tags %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">{% endblock %}

{% block coltype %}colM{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
</div>
{% endblock %}
{% endif %}

{% block content %}
<div id="content-main">
    <form class="forms-form" method="POST" action="{% url 'employee:add_groups' selected=selected_ids %}">
        {% csrf_token %}
        {{form.as_p}}
        {% block submit-row %}
            <input type="submit" value="Add groups" class="green">
        {% endblock %}
    </form>
</div>
{% endblock %}

employee/templates/employee/automatically_sign_form.html
{% extends "theme/base.html" %}
{% load grouping %} {% load crispy_forms_tags %} {% load static %} {% load i18n %}
{% block title %} - {% if request.user.preferred_name %}{{request.user.preferred_name}} {% else %} {{request.user.first_name}} {% endif %} {{request.user.last_name}} - Auto-sign form{% endblock %}
{% block content %}
<div class="flex flex-col max-w-5xl mx-auto mt-10">
    <h1 class="text-3xl">{% blocktranslate with formName=paperwork.form %} Automatically Sign {{formName}} {% endblocktranslate %}</h1>
    <div class="p-5 m-4 text-black bg-red-300 rounded-sm"> 
        <h2>
            By signing this form electronically using your signature, you agree to the following:
        </h2>
        {% blocktranslate with formName=paperwork.form formUrl=paperwork.form.form_pdf.url %} 
        <ul class="list-disc">
            <li class="text-black">
                Your signature will be binding and held to the same standard as a physical signature
            </li>
            <li class="text-black">
                Clicking "Sign using Signature on File" shows your clear intent to sign <a class="underline" href="{{formUrl}}">{{formName}}</a>
            </li>
            <li class="text-black">
                You've been given the option to sign and submit this form manually (just use the upload functionality instead if you wish)
            </li>
            <li class="text-black">
                You'll wait patiently for a few seconds (up to a minute) after hitting sign. Gary is a snail and it takes him a second to pull up your info and fill it out.
            </li>
        </ul>
        {% endblocktranslate %}
    </div>
    <div class="mt-5">
        {% crispy form %}
    </div>
</div>
<style>
    label {
        color: white!important;
    }
    .clearablefileinput {
        color:rgb(228, 225, 225);
        border-radius: 2px;
    }
    #div_id_pdf a {
        text-decoration: underline;
        margin-right: 1rem;
    }
</style>
{% endblock %}

employee/templates/employee/change_password.html
{% extends "theme/base.html" %}
{% load grouping %} {% load crispy_forms_tags %} {% load static %}
{% block title %} - {% if request.user.preferred_name %}{{request.user.preferred_name}} {% else %} {{request.user.first_name}} {% endif %} {{request.user.last_name}} - Change Password{% endblock %}

{% block content %}
<div class="flex flex-col max-w-5xl mx-auto mt-10">
    <h1 class="text-3xl">Change Password</h1>
    <div class="mt-5">
        {% crispy form %}
    </div>
</div>
<style>
    label {
        color: white!important;
    }
    ul {
        color: rgb(228, 225, 225)!important;
    }
</style>
{% endblock %}

employee/templates/employee/mass_assign_paperwork.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}
{% load gig_admin %}
{% load crispy_forms_tags %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">{% endblock %}

{% block coltype %}colM{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
</div>
{% endblock %}
{% endif %}

{% block content %}
<div id="content-main">
    <form class="forms-form" method="POST" action="{% url 'employee:mass_assign' selected=selected_ids %}">
        {% csrf_token %}
        {{form.as_p}}
        {% block submit-row %}
            <input type="submit" value="Assign forms + send emails" class="green">
        {% endblock %}
    </form>
</div>
{% endblock %}

employee/templates/employee/office_hours.html
{% extends "theme/base.html" %} {% load grouping %} {% load crispy_forms_tags %} {% load static %}
{% block title %}- Office Hours{% endblock %}
{% load gig_components %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.formset.js' %}" type="text/javascript"> </script>
<div class="max-w-5xl m-4 md:mx-auto">
    <h1 class="text-4xl">Manager Office Hours</h1>
    <h2 class="text-xl">Don't worry if it looks like your shifts are dissapearing! Only shifts that are unprocessed will show up here. If they're contested or processed they'll be on your <a class="underline" href="{% url 'employee:overview'%}">User</a> page but not here</h2>
    <form method="POST">
        {% csrf_token %}
        {% for ofform in forms.values %}
        <div id="{{ofform.prefix}}" class="p-4 m-2 bg-[#333333] rounded-sm">
            {% with formname=form_meta|get_item:ofform.prefix %}
            <h2>
                Paid at <code class="p-1 bg-black">{{formname.rate}}</code> Rate
            </h2>
            {% endwith %}
            {{ ofform.management_form|crispy }}
            {% for form in ofform.forms %}
            <div class="flex space-x-2">
                {% for error in form.errors.values %}
                    <div class="p-2 font-bold bg-red-500">
                        {{error.0}}
                    </div>
                {% endfor %}
            </div>
            <div class="{% cycle 'row1' 'row2' %} formset row-{{ofform.prefix}} flex">
                <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2">
                    {% for field in form.visible_fields %}
                    <div>
                        {# Include the hidden fields in the form #}
                        {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        {% endif %}
                        {{ field.errors.as_ul }}
                        {{ field|as_crispy_field }}
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
        <script type="text/javascript">
            $('.row-{{ofform.prefix}}').formset({
                addText: 'Add Shift',
                deleteText: '✕',
                deleteCssClass: 'delete-row my-auto bg-black w-min px-4 py-2',
                prefix: '{{ ofform.prefix }}',
                {% if not ofform.errors %}
                hideLastAddForm: true,
                {% endif %}
            });;
        </script>
        {% endfor %}
        <button class="m-2 bg-[#009961] py-4 px-2" type="submit">Submit</button>
    </form>
</div>
<style>

    /* Hide bad formatted errors */
    .errorlist {
        display: none;
    }

    label {
        color: white !important;
    }

    .add-row {
        padding: 1rem;
        background-color: #009961;
        display: block;
        width: max-content;
        margin: .5rem 0;
    }
    .text-gray-600 {
        color: white!important;
        font-size: .5rem;
    }

    @media (min-width: 768px) {
        .delete-row {
            margin-bottom: .75rem;
        }
    }

    .delete-row {
        margin-left: .5rem;
        height: max-content;

    }
</style>
{% endblock %}

employee/templates/employee/signup.html
{% extends "theme/base.html" %} {% load grouping %} {% load crispy_forms_tags %} {% load i18n %}
{% block title %}Signup{% endblock %}
{% block nav %}{% endblock %}
{% block content %}
<div class="m-5">
    <h1 class="text-5xl">
        Signup for <span class="font-stencil">BSSL S.L.U.G.S</span>
    </h1>
    <h2 class="mt-4 text-lg">
        {% blocktranslate %}
        We're glad to have you join us! Welcome to your first interaction with SLUGS.
        This is our custom system that we use to book, staff, and manage shows. We're
        going to get you setup with an account real quick.
        {% endblocktranslate %}
    </h2>
    {% crispy form %}
</div>
<style>
    label {
        color: white!important;
    }
    small {
        color: white!important
    }
</style>
{% endblock %}
{% block footer %}{% endblock %}

employee/templates/employee/signup_complete.html
{% extends "theme/base.html" %} {% load grouping %} {% load crispy_forms_tags %}
{% block title %}Signup Complete{% endblock %}
{% block nav %}{% endblock %}

{% block content %}
<div class="max-w-5xl mx-auto mt-10">
    <h1 class="text-6xl text-center">
        Thank you!
    </h1>
    <h2 class="my-6 text-2xl text-center">
        We will reach out to you as soon as your account is ready for use.
    </h2>
    <div class="flex p-4 space-x-4 text-black bg-yellow-300 rounded">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-20 h-20 my-auto text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <span class="my-auto">
            You will <b>NOT</b> be able to sign in immediately. Do not try to sign in (it won't work) or send us emails saying your account doesn't work. We manually go through and activate accounts in order to ensure that only BSSL employees have access to <span class="font-stencil">S.L.U.G.S</span>. You will receive an email once your SLUGS account is activated. Let the excited waiting begin...
          </span>
    </div>
</div>
{% endblock %}
{% block footer %}{% endblock %}

employee/templates/employee/upload_form.html
{% extends "theme/base.html" %}
{% load grouping %} {% load crispy_forms_tags %} {% load static %}
{% block title %} - {% if request.user.preferred_name %}{{request.user.preferred_name}} {% else %} {{request.user.first_name}} {% endif %} {{request.user.last_name}} - Upload Form{% endblock %}
{% block content %}
<div class="flex flex-col max-w-5xl mx-auto mt-10">
    <h1 class="text-3xl">Upload {{paperwork.form}}</h1>
    <div class="mt-5">
        {% crispy form %}
    </div>
</div>
<style>
    label {
        color: white!important;
    }
    ul {
        color: rgb(228, 225, 225)!important;
    }
    .clearablefileinput {
        color:rgb(228, 225, 225);
        border-radius: 2px;
    }
    #div_id_pdf a {
        text-decoration: underline;
        margin-right: 1rem;
    }
</style>
{% endblock %}