SLUGS/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from SLUGS import views
from django.contrib.auth import views as auth_views
from gig.views import AttachmentDownload, VendorDownload
from employee.views import FormDownload, FilledFormDownload
from finance.views import EstimateDownload
from django.views.generic.base import RedirectView


urlpatterns = [
    path("unicorn/", include("django_unicorn.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("hijack/", include("hijack.urls")),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('.well-known/openid-configuration', RedirectView.as_view(url='/openid/.well-known/openid-configuration', permanent=False), name='openid-configuration'),
    path("admin/", admin.site.urls),
    path(
        "media/forms/<path:relative_path>", FormDownload.as_view(), name="download_form"
    ),
    path(
        "media/uploads/<u_pk>/<path:relative_path>",
        FilledFormDownload.as_view(),
        name="download_form",
    ),
    path(
        "media/estimates/<path:relative_path>",
        EstimateDownload.as_view(),
        name="download_estimate",
    ),
    path(
        "media/attachments/<path:relative_path>",
        AttachmentDownload.as_view(),
        name="download_attachment",
    ),
    path(
        "media/vendors/<path:relative_path>",
        VendorDownload.as_view(),
        name="download_vendor_form",
    ),
    path(
        "auth/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_html_email.html"
        ),
    ),
    path("auth/", include("django.contrib.auth.urls"), name="auth"),
    path("utils/", include("utils.urls")),
    path("", views.index.as_view(), name="index"),
    path("kiosk/", views.kiosk.as_view(), name="kiosk"),
    path("employee/", include("employee.urls")),
    path("gig/", include("gig.urls")),
    path("equipment/", include("equipment.urls")),
    path("training/", include("training.urls")),
    path("finance/", include("finance.urls")),
]

gig/urls.py
from django.urls import path
from . import views

app_name = "gig"
urlpatterns = [
    path("signup/", views.workSignup.as_view(), name="signup"),
    path("list/", views.gigList.as_view(), name="list"),
    path("joblist/", views.DistinctGigJobsList.as_view(), name="joblist"),
    path("booking/", views.BookingOverview.as_view(), name="booking_overview"),
    path("<gig_id>/", views.gigIndex.as_view(), name="showView"),
    path(
        "<gig_id>/staff_email_template",
        views.generateEmailTemplate.as_view(),
        name="staff_email_template",
    ),
]

gig/models.py
from datetime import datetime
import decimal
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.forms import ValidationError
from django.utils import timezone
from django.utils.html import format_html
from django.urls import reverse
from tinymce.models import HTMLField
from django.contrib.auth.models import Group
from django.db.models import Q, Sum

import client.models as client
import location.models as location
import employee.models as employee

DEPARTMENTS = [
    ("L", "Lighting"),
    ("S", "Sound"),
    ("M", "Manager"),
    ("O", "Other"),
    ("T", "Staging"),
]

DELIVERY_METHODS = [
    ("H", "Vendor Delivery"),
    ("S", "Vendor Shipping"),
    ("P", "BSSL Delivery"),
    ("B", "BSSL Shipping"),
    ("O", "Other Arrangements"),

]


class SubcontractedEquipmentInstance(models.Model):
    equipment = models.ForeignKey("equipment.VendorEquipment", on_delete=models.PROTECT)
    subcontracted_equipment = models.ForeignKey("SubcontractedEquipment", on_delete=models.CASCADE)
    qty = models.IntegerField(default=1)
    description = models.CharField(max_length=200, blank=True, null=True)


class SubcontractedEquipment(models.Model):
    equipment = models.ManyToManyField("equipment.VendorEquipment", through="SubcontractedEquipmentInstance")
    vendor = models.ForeignKey("equipment.Vendor", on_delete=models.PROTECT)
    arrival = models.DateTimeField()
    returned = models.DateTimeField()
    delivery_method = models.CharField(max_length=1, choices=DELIVERY_METHODS)
    return_method = models.CharField(max_length=1, choices=DELIVERY_METHODS)
    purchase_order = models.CharField(max_length=64, null=True, blank=True)
    vendor_visible_to_client = models.BooleanField(default=False)
    client_provided = models.BooleanField(default=False)
    notes = HTMLField(blank=True, null=True)
    gig = models.ForeignKey("Gig", on_delete=models.CASCADE)
    signed_agreement = models.FileField(upload_to="vendors", null=True, blank=True)

    def get_printout_link(self):
        return format_html(
                "<a href='%s?time=%s'>%s</a><br>"
                % (
                    reverse("finance:vendor", args=(self.id,)),
                    datetime.now(),
                    f"Print Subcontracted Equipment Form - {self.vendor}",
                )
            ) if not self.client_provided else "Provided by client"

    def __str__(self):
        return f"{self.vendor} - {self.gig}"

    class Meta:
        verbose_name_plural = "Subcontracted Equipment"


class Gig(models.Model):
    """
    A BSSL Show.
    """
    name = models.CharField(max_length=200)
    notes = HTMLField(
        blank=True,
        null=True,
        help_text="This will show up on the showview page and the estimate as 'ATTN ENG'",
    )
    manager_only_notes = HTMLField(blank=True, null=True)
    setup_by = models.DateTimeField(verbose_name="Setup By")
    start = models.DateTimeField(verbose_name="Gig start time")
    end = models.DateTimeField(verbose_name="Gig end time")
    org = models.ForeignKey(client.Organization, models.PROTECT)
    contact = models.ForeignKey(client.OrgContact, models.PROTECT, null=True)
    location = models.ForeignKey(location.Location, models.PROTECT)
    day_of_show_notes = models.TextField(blank=True)
    archived = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    available_for_signup = models.DateField(
        blank=True,
        null=True,
        verbose_name="Date Available for Signup",
        help_text="If left blank, this value will be set to 7 days prior to the start date.",
    )
    systems = models.ManyToManyField("equipment.System", through="SystemInstance")
    subcontracted_equipment = models.ManyToManyField("SubcontractedEquipment", related_name="vendor_equipment")
    attachments = GenericRelation("utils.Attachment")

    def calculate_outflow(self):
        outflow = decimal.Decimal(0.00)
        for job in self.job_set.all():
            job_outflow = job.shifts.all().aggregate(Sum("cost"))['cost__sum']
            outflow += job_outflow if job_outflow is not None else decimal.Decimal(0.00)
        return round(outflow, 2)

    def get_staff_link(self):
        return format_html(
            "<a href='%s'>%s</a>"
            % (reverse("admin:gig_gig_staff", args=(self.id,)), "Staff Show")
        )

    def send_staffing_email(self):
        return format_html(
            "<a href='%s'>%s</a>"
            % (reverse("admin:gig_gig_email", args=(self.id,)), "Send staffing email")
        )

    def __str__(self):
        return (
            self.name
            + " - "
            + str(self.org.name)
            + " - "
            + str(timezone.localtime(self.start).strftime("%m/%d/%Y"))
            + (" [UNPUBLISHED]" if not self.published else "")
            + (" [ARCHIVED]" if self.archived else "")
        )  # noop

    def clean(self):
        # Validation: Gig cannot end before it starts
        if self.end < self.start:
            raise ValidationError("Gig cannot end before it starts")

        # Validation - Gig cannot start before it is setup
        if self.start < self.setup_by:
            raise ValidationError("Gig cannot start before it is setup")

    def save(self, *args, **kwargs):
        if self.available_for_signup is None:
            self.available_for_signup = self.start - timezone.timedelta(days=7)
        super().save(*args, **kwargs)

    def __init__(self, *args, **kwargs):
        super(Gig, self).__init__(*args, **kwargs)
        self.__loadin_depts__ = []


class LoadIn(models.Model):
    """
    A Load in for a show. Contains: the time employees should report to the shop (Shop Time), the time BSSL is to arrive at the venue (Load in time) and the time BSSL is to be done unpacking and go home (Load out time).
    """
    gig = models.ForeignKey(Gig, on_delete=models.CASCADE)
    department = models.CharField(choices=DEPARTMENTS, max_length=1)
    note = models.CharField(max_length=128, blank=True, null=True, help_text="Use this only when further explaintation is needed as to which shift this loadin is for.")
    shop_time = models.DateTimeField()
    load_in = models.DateTimeField()
    load_out = models.DateTimeField()

    def __str__(self):
        return f"{self.department} - {self.gig}"


class SystemInstance(models.Model):
    """
    An instance of a :model:`equipment.System` applied to a :model:`gig.Gig`. Contains the addons and employees for this show.
    """
    system = models.ForeignKey("equipment.System", on_delete=models.PROTECT)
    addons = models.ManyToManyField(
        "equipment.SystemAddon", through="gig.AddonInstance", blank=True
    )
    gig = models.ForeignKey(Gig, on_delete=models.CASCADE)
    employees = models.ManyToManyField(employee.Employee, through="Job")

    class Meta:
        verbose_name = "Rented System"
        verbose_name_plural = "Rented Systems"

    def __str__(self):
        return f"{self.system}"


class AddonInstance(models.Model):
    """
    An instance of a :model:`equipment.SystemAddon` applied to a :model:`gig.Gig`. Contains the addons and employees for this show.
    """
    addon = models.ForeignKey("equipment.SystemAddon", on_delete=models.CASCADE)
    systemInstance = models.ForeignKey("gig.SystemInstance", on_delete=models.CASCADE)
    description = models.CharField(max_length=200, blank=True, null=True)
    qty = models.IntegerField(default=1)

    class Meta:
        verbose_name = "Addon"
        verbose_name_plural = "Addons"


class Job(models.Model):
    """
    A Job that must be worked as part of a :model:`gig.Gig`.
    """
    gig = models.ForeignKey(Gig, on_delete=models.CASCADE)
    employee = models.ForeignKey(
        employee.Employee, on_delete=models.SET_NULL, null=True, blank=True
    )
    position = models.ForeignKey(Group, on_delete=models.PROTECT)
    linked_system = models.ForeignKey(
        SystemInstance, on_delete=models.PROTECT, null=True, blank=True
    )
    department = models.CharField(choices=DEPARTMENTS, max_length=1)
    is_test = models.BooleanField(default=False)
    shifts = GenericRelation("finance.Shift", related_query_name="job")

    def __str__(self):
        return f"{self.gig.name} - {self.gig.org}"


class JobInterest(models.Model):
    """
    Interest from an employee to work a :model:`gig.Job`.
    """
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    employee = models.ForeignKey(employee.Employee, on_delete=models.CASCADE)
    submitted = models.DateTimeField(auto_now_add=True)
    would_be_test = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.employee} - {self.job.gig}"


class BingoBoard(models.Model):
    gig = models.ForeignKey(Gig, on_delete=models.CASCADE)
    available_for_play = models.BooleanField(default=True)
    tiles = models.ManyToManyField("BingoTile", through="TileOnBoard")
    bingo_achieved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.gig} Bingo Board ({'open' if self.available_for_play else 'closed'})"

    def choose_random_tile(self, currently_on_board=[]):
        depts_in_gig = set([d.department for d in self.gig.systems.all()]+["A"])
        available = BingoTile.objects.filter(Q(department__in=depts_in_gig) & Q(in_pool=True) & ~Q(pk__in=currently_on_board))
        chosen = available.order_by("?").first()
        tmp = currently_on_board.append(chosen.pk) if currently_on_board is not None else [chosen.pk]
        return (chosen, currently_on_board) if chosen is not None else None


    def save(self, *args, **kwargs):
        if self.pk is None:
            super().save(*args, **kwargs)
        currently_on_board = [t.pk for t in self.tiles.all()]
        # If not enough tiles on board, attempts to find unique tiles, if cannot find enough unique it resorts to choosing duplicates
        while self.tiles.count() < 16:
            try:

gig/templates/gig/booking.html
{% extends "theme/base.html" %} {% load unicorn %} {% load grouping %} {% load crispy_forms_tags %} {% load static %} {% block title %} - Booking Homepage{% endblock %} {% block headincludes %}{% unicorn_scripts %}{% endblock %} {% block content %}
<div class="max-w-5xl m-4 md:mx-auto">
    <h1 class="text-4xl">Booking Overview</h1>
    <div class="flex">
        <a class="mx-auto" href="{% url 'admin:finance_estimate_add' %}"> <button class="px-8 py-4 mt-4 text-white bg-[#009961] text-xl rounded-sm">Create Estimate</button> </a>
    </div>
        
    {% if gig_wo_estimate.count > 0 %}
    <div>
        <h2 class="mt-5 text-2xl">Gigs without Estimates</h2>
        <div class="bg-red-500 text-black p-4">
            <b>There are Gigs without estimates!</b>
            <ul class="list-disc ml-6">
            {% for gig in gig_wo_estimate %}
                <li>
                    {{gig}}
                </li>
            {% endfor %}
            </ul>
            <b>Go create estimates for these gigs please :)</b>
        </div>
    </div>
    {% endif %}

    <div>
        <h2 class="mt-5 text-2xl">Outstanding Bookings</h2>
        <h6 class="text-sm">These are all bookings that have not been finalized and are after today's date. Bookings that have been postponed or are in limbo are found at the bottom of the list.</h6>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            {% now "Y-m-d" as today_date %}
            {% for estimate in outstanding_bookings %}
            <div class="flex flex-col p-4 text-center text-black {% if estimate.three_weeks_prior|date:'Y-m-d' < today_date %}bg-red-300{% else %}bg-white{% endif %} rounded-sm">
                {% if estimate.three_weeks_prior|date:'Y-m-d' < today_date %}
                    <p class="text-lg font-bold">EVENT IS LESS THAN 3 WEEKS OUT</p>
                {% endif %}
                <p class="text-2xl">{{estimate.gig.name}}</p>
                {% if estimate.status == "L" %}
                <p class="text-lg font-bold">ESTIMATE IN LIMBO / POSTPONED</p>
                {% endif %}
                <p class="text-xl">{{estimate.gig.org}}</p>
                <p class="text-lg">{{estimate.gig.start|date:"n/j/y"}}</p>
                <p class="text-md">${{estimate.total_amt|floatformat:2}}</p>
                <div class="max-h-96 flex space-x-2 overflow-scroll">
                    <div class="flex flex-col mx-auto mb-4 space-y-2">
                        {% for system in estimate.gig.systeminstance_set.all %}
                        <div class="flex flex-col p-4 mx-auto text-white bg-gray-800 rounded-sm">
                            <h3 class="text-2xl text-center">{{system.system.get_department_display}}</h3>
                            <h3 class="text-lg text-center ">{{system.system.name}}</h3>
                            {% if system.addons %}
                            <ul class="text-center">
                                {% for addon in system.addons.all %}
                                <li>+ {{addon}}</li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    {% if estimate.gig.manager_only_notes or estimate.gig.notes %}
                    <div class="">
                        {% if estimate.gig.manager_only_notes %}
                        <div class="p-2 bg-gray-300 text-md">
                            <p class="text-center font-bold">MANAGER ONLY NOTES:</p>
                            {{estimate.gig.manager_only_notes|safe }}
                        </div>
                        {% endif %} {% if estimate.gig.notes %}
                        <div class="p-2 bg-gray-300 text-md">
                            <p class="text-center font-bold">ATTN ENG:</p>
                            {{estimate.gig.notes|safe }}
                        </div>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
                <div class="flex mt-auto mb-0 space-x-2">
                    <a class="flex-1" href="{% url 'admin:finance_estimate_change' estimate.pk %}"> <button class="px-4 py-2 mt-2 text-white bg-black rounded">Goto Estimate</button> </a>
                    <a class="flex-1" href="{% url 'admin:gig_gig_change' estimate.gig.pk %}"> <button class="px-4 py-2 mt-2 text-white bg-black rounded">Goto Gig</button> </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div>
        <h2 class="mt-5 text-2xl">Event Calendar</h2>
        <h6 class="text-sm">Bookings both reserved and tentative appear here. Tentative events appear with "[TENTATIVE]" in the title</h6>
        <div>
            <iframe id="open-web-calendar" style="background:url('https://raw.githubusercontent.com/niccokunzmann/open-web-calendar/master/static/img/loaders/circular-loader.gif') center center no-repeat;" src="https://open-web-calendar.hosted.quelltext.eu/calendar.html?url=https%3A%2F%2Fslugs.bssl.binghamtonsa.org%2Futils%2Flatest%2Fevents.ics&amp;url=https%3A%2F%2Fslugs.bssl.binghamtonsa.org%2Futils%2Flatest%2Ftentative_events.ics&amp;title=BSSL%20MANAGER%20EVENT%20CALENDAR&amp;skin=dhtmlxscheduler.css&amp;css=.dhx_cal_navline%2C%20.dhx_scale_bar%2C%20.dhx_cal_container%2C%20.dhx_cal_header%20%7Bbackground-color%3A%20black%3B%7D%0A.event%2C%20.dhx_cal_tab.active%2C%20.dhx_cal_tab.active%3Ahover%20%7Bbackground-color%3A%20%23009961%3B%7D%20.dhx_month_head%2C%20.dhx_cal_tab%2C%20.dhx_cal_today_button%20%7Bcolor%3A%20%23009961%3B%7D%20.dhx_cal_tab%2C%20.dhx_cal_tab.active%20%7Bborder-color%3A%20%23009961%3B%7D%0A.dhx_month_body%2C%20.dhx_month_head%2C%20.dhx_cal_container%20%7B%20background-color%3A%20black%3B%20%7D%0A.dhx_after%20.dhx_month_body%2C%20.dhx_before%20.dhx_month_body%2C%20.dhx_after%20.dhx_month_head%2C%20.dhx_before%20.dhx_month_head%20%7B%20background-color%3A%20gray%3B%20%7D%0A.event%20%7B%0Acolor%3A%20white%0A%7D%0A.dhx_cal_date%20%7B%0Acolor%3A%20white!important%3B%0A%7D.dhx_cal_next_button%2C%20.dhx_cal_prev_button%20%7B%0Afilter%3A%20invert(1)%3B%0A%7D&amp;target=_blank"
                sandbox="allow-scripts allow-same-origin allow-popups" allowTransparency="true" scrolling="no" frameborder="0" height="600px" width="100%"></iframe>
        </div>
    </div>
</div>
{% endblock %}

gig/templates/gig/list.html
{% extends "theme/base.html" %}
{% load grouping %} {% load crispy_forms_tags %} {% load static %}
{% block title %} - Shows{% endblock %}

{% block content %}
<div class="max-w-5xl mx-auto mt-10">
    {% if signup_open %}
    <a class="m-4" href="{% url 'index' %}">
        <div
            class="flex max-w-5xl px-12 py-6 mx-auto text-center text-black transition bg-red-300 rounded-sm hover:bg-red-200">
            <div style="margin: auto;"> Looking for work signup? It's on the homepage. Click here or the snail above to go there. You'll find it in a box much like this one.</div>
        </div>
    </a>
    {% endif %}
    <h1 class="text-4xl text-bold">
        Shows
    </h1>
    <div class="my-4 md:mx-20">
        <table style="border-spacing: 1rem 1rem;" class="w-full table-auto">
            <thead class="border-b-2 border-white">
                <tr>
                    <td>
                        Name
                    </td>
                    <td class="hidden md:inline">
                        Organization
                    </td>
                    <td>
                        Location
                    </td>
                    <td>
                        When
                    </td>
                </tr>
            </thead>
            <tbody>
                {% for gig in gigs %}
                <tr tabindex="0" onclick="window.location='{% url 'gig:showView' gig.id %}'" class="cursor-pointer even:bg-[#1F1F1F] odd:bg-[#333333] hover:bg-gray-700">
                    <td class="pl-2">
                        {{gig.name}}
                    </td>
                    <td class="hidden pl-2 md:table-cell">
                        {{gig.org}}
                    </td>
                    <td class="py-4 pl-2">
                        {{gig.location}}
                    </td>
                    <td class="pl-2">
                        {{gig.start}}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

gig/templates/gig/signup.html
{% extends "theme/base.html" %}
{% load unicorn %}
{% load grouping %} {% load crispy_forms_tags %} {% load static %} {% load i18n %}
{% block title %} - Signup for work{% endblock %}

{% block headincludes %}{% unicorn_scripts %}{% endblock %}
{% block content %}
<div class="max-w-5xl m-4 space-y-4 md:mx-auto">
    <h1 class="text-3xl">
        Sign up for upcoming shows!
    </h1>
    <h3 class="text-lg">
        Your updates are saved automagically. Just click.
    </h3>
    <h4 class="mb-5">{% translate "As always, remember that expressing interest in a job does <b>NOT</b> mean you have been staffed. We will reach out to you when/if you're staffed for the position. You're also welcome to sign up for multiple positions on a show." %}</h4>
    {% if gigs|length > 0 %}
    {% else %}
    <div class="flex flex-col p-4 pb-0 pl-0 text-xl text-center text-black bg-white rounded-sm">
        You have full permission to go yell at the managers. All the spots are filled yet here we are...
        <img class="w-16" src="{% static 'gig/img/whoops.png' %}" alt="Awkward..."/>
    </div>
    {% endif %}
    {% for gig in gigs %}
    <div class="w-full px-4 py-2 text-black bg-white">
        <a class="underline" href="{% url 'gig:showView' gig_id=gig.pk %}"><h2 class="text-2xl">
            {{gig.name}}
        </h2></a>
        <p>
            {{gig.start}} - {{gig.end}}
        </p>
        <p>
            Location: {{gig.location}}
        </p>
        {% if gig.notes %}
            <div class="p-4 m-2 mx-auto bg-gray-300 rounded max-w-prose">
                {{gig.notes|safe}}
            </div>
        {% endif %}
        <div class="flex flex-col mx-auto w-max md:flex-row">
            {% for loadin in gig.loadin_set.all %}
                <div class="p-4 m-2 border-2 border-black border-solid rounded w-max">
                    <p class="text-lg font-bold">{{loadin.get_department_display}} {% if loadin.note %}<sub>{{loadin.note}}</sub>{% endif %}</p>
                    <div class="flex space-x-2">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 my-auto mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
                        </svg>
                        {{loadin.shop_time}}
                    </div>
                    <div class="flex space-x-2">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                        </svg>
                        {{loadin.load_in}}
                    </div>
                    <div class="flex space-x-2">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 19l-7-7 7-7m8 14l-7-7 7-7" />
                        </svg>
                        {{loadin.load_out}}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="flex flex-col mx-auto mb-4 space-y-2 sm:space-y-0 sm:space-x-2 w-max md:flex-row">
            {% for system in gig.systeminstance_set.all %}
                <div class="flex flex-col p-4 mx-auto text-black bg-white border-2 border-black rounded-sm">
                    <h3 class="text-2xl text-center">{{system.system.get_department_display}}</h3>
                    <h3 class="text-lg text-center ">{{system.system.name}}</h3>
                    {% if system.addons %}
                    <ul class="text-center">
                        {% for addon in system.addons.all %}
                        <li>+ {{addon}}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        {% unicorn 'gigSignup' gig_id=gig.pk u_id=request.user.id %}
    </div>
    {% endfor %}
    <div class="p-4 my-2 text-black bg-white">
        <h2>
            As a reminder. You may sign up for the following jobs.
        </h2>
        <div >
            {% for group in request.user.groups.all %}
            <div class="inline-block p-2 m-2 text-white bg-black rounded-sm">{{group}}</div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}